# path: GroppiSite/dev/docker-compose

services:
  groppi_DB:
    container_name: groppi_DB
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=1234
    ports:
      - 3307:3306   # host:container — 3306 host occupata da mariadb/mysql locale
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./../mariadb:/var/lib/mysql
      - ./../database:/docker-entrypoint-initdb.d/:ro
  groppi_app:
    depends_on:
      groppi_DB:
        condition: service_healthy
    container_name: groppi_app
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./../app:/srv/app
      - ./logs:/root/.npm/_logs
    environment:
      - JWT_SECRET=06516024d20f36f491be7f46def1b6a9fb86ea60036b41be9d94d1dd2e677607
      - DEMO=true
